area_blog:
    type: rest
    resource: "@AreaBlogBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

ng-static:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'AreaBlogBundle::index.html.twig'
