parameters:
#    area_blog.example.class: Area\BlogBundle\Example

services:
#    area_blog.example:
#        class: %area_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
